name: .NET Core Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Clean Solution
      run: dotnet Clean
      
    - name: Install dependencies
      run: dotnet restore

    - name: Set environment to Production
      run: echo "ASPNETCORE_ENVIRONMENT=Production" >> $GITHUB_ENV
   
    - name: Build the project
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      env:
        ASPNETCORE_ENVIRONMENT: Production
      run: dotnet test --no-build --verbosity normal --configuration Release
